FROM mdillon/postgis:10-alpine
ENV POSTGRES_USER=postgres
ENV POSTGRES_DATA=/home/postgres/cpd_db

WORKDIR /app

COPY . /app

RUN mkdir /home/postgres
RUN chown postgres /home/postgres
RUN su postgres -c /app/doc/run-as-postgres

RUN echo "host all  all    0.0.0.0/0  trust" >> $POSTGRES_DATA/pg_hba.conf

#
#   /home/postgres/cpd_db  <-- for actual db and config 
#   /home/postgres/CPD     <-  for schema,sql script,csv data 
#


